[project]
name = "aoc2025"
version = "0.1.0"
description = "A0C 2025"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "networkx>=3.6.1",
    "pulp>=3.3.0",
    "shapely>=2.1.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.0",
    "ruff>=0.14.7",
]
